advancements
eTh3r-network/vapor pull request #6
Opened 2024-03-11 13:57 UTC by aaryswastaken

2024-03-15 11:52 UTC, aaryswastaken commented
The key retrieval logic has been implemented but not tested by any way

2024-03-18 15:28 UTC, Portevent requested changes
Two typos, seems alrigth otherwise

2024-03-18 15:28 UTC, Portevent commented on ether/proto0001.go
> +					c.log.Warn("user could not be found")
Isn't it checking if the response to the client went wrong ? This log probably need to be displayed anyway if we enter `conn == nil`

2024-03-18 15:28 UTC, Portevent commented on ether/proto0001.go
> +			respBuff = append(respBuff[:], response[:]) // prepend the pck id
`respBuff = append(respBuff[:], keyBuff[:])`

2024-03-18 16:10 UTC, Portevent approved these changes

2024-03-18 16:10 UTC, merged